/*******************************************************************************
 * Copyright 2022 Adobe
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
(function($, Granite) {
    "use strict";

    var EDIT_DIALOG = ".cmp-adaptiveform-container__editdialog",
        DOR_TYPE_SELECTOR = EDIT_DIALOG + " .cmp-adaptiveform-container__dortypeselector",
        DOR_TYPE = EDIT_DIALOG + " .cmp-adaptiveform-container__dortype",
        AUTO_GENERATE_DOR_PANEL = EDIT_DIALOG + " .cmp-adaptiveform-container__dordetails",
        DOR_TEMPLATE_REF_FIELD = EDIT_DIALOG + " .cmp-adaptiveform-container__dortemplateref",
        Utils = window.CQ.FormsCoreComponents.Utils.v1;

    // Constants for DOR selection types
    var DOR_NONE = "none",
        DOR_SELECT = "select",
        DOR_GENERATE = "generate",
        FM_AF_ROOT = "/content/forms/af/",
        DAM_ROOT = "/content/dam/formsanddocuments/",
        CONTAINER = "/guideContainer",
        METADATA = "/metadata";

    var DEFAULT_VALUE_MAP = {
        "dorPath": "/content/dam/formsanddocuments",
        "dorName": "auto-generated-dor",
        "dorTitle": "Auto-generated Document of Record"
    };

    function manageDeleteFields(dialog, filedArray,shouldDelete) {
        for (var fieldName of filedArray) {
            var field = dialog.find('[name="./' + fieldName + '"]');
            var foundationField = null;
            if (field.length !== 0) {
                foundationField = field.adaptTo("foundation-field");
             }
            var deleteField = dialog.find('input[name="./' + fieldName + '@Delete"]');
            if (shouldDelete) {
                if (foundationField) {
                    foundationField.setValue('');
                    foundationField.setRequired(false);
                    foundationField.setInvalid(false);
                }
                if (deleteField.length === 0) {
                    // Create the @Delete field if it doesn't exist
                    var deleteInput = $('<input>', {
                        type: 'hidden',
                        name: './' + fieldName + '@Delete',
                        value: ''
                    });
                    dialog.find('form').append(deleteInput);
                }
            } else {
                deleteField.remove();
                foundationField.setRequired(true);
                if (DEFAULT_VALUE_MAP[fieldName]) {
                    foundationField.setValue(DEFAULT_VALUE_MAP[fieldName]);
                }
            }
        }
    }

    function manageElementVisibility(dialog, elements, shouldShow) {
        for (var element of elements) {
            if (shouldShow) {
                element.removeAttr('hidden');
            } else {
                element.attr('hidden', true);
            }
        }
    }

    function manageFDViewPayload(dialog, shouldDelete) {
        var form = dialog.find('form');
        if (shouldDelete) {
            form.find('input[name="./fd:view/print/jcr:created"]').remove();
            form.find('input[name="./fd:view/print/jcr:lastModified"]').remove();
            form.find('input[name="./fd:view/print/sling:resourceType"]').remove();
            form.find('input[name="./fd:view/print/metaTemplateRef"]').remove();
        } else {
            form.append($('<input>', {
                type: 'hidden',
                name: './fd:view/print/jcr:created',
                value: ''
            }));
            form.append($('<input>', {
                type: 'hidden',
                name: './fd:view/print/jcr:lastModified',
                value: ''
            }));    
            form.append($('<input>', {
                type: 'hidden',
                name: './fd:view/print/sling:resourceType',
                value: 'fd/af/authoring/components/dor/dorProperties'
            }));
            form.append($('<input>', {
                type: 'hidden',
                name: './fd:view/print/metaTemplateRef',
                value: '/libs/fd/af/dor/templates/defaultTemplate.xdp'
            }));
        }
    }

    function isFormEditor(){
        return Granite.author.page.path.startsWith(FM_AF_ROOT);
    }

    function handleDorTypeSelection(dialog) {
        var dorTypeSelector = dialog.find(DOR_TYPE_SELECTOR)[0];
        var dorTemplateRefField = dialog.find(DOR_TEMPLATE_REF_FIELD);
        var autoGenerateDorPanel = dialog.find(AUTO_GENERATE_DOR_PANEL);
        var dorType = dialog.find(DOR_TYPE)[0];

        if (!dorTypeSelector || !dorType) {
            return;
        }

        // Initialize DOR type from stored value, default to "none" if not set
        dorType.value = dorType.value ? dorType.value : DOR_NONE;


        // Check the appropriate radio button
        var radioButton = dorTypeSelector.querySelector('input[value="' + dorType.value + '"]');
        if (radioButton) {
            radioButton.checked = true;
        }

        var updateDorUIBasedOnSelection = function(event) {
            var selectedValue = event.target.value;
            dorType.value = selectedValue;
            var deleteFields = [],
                persistFields = [],
                showElements = [],
                hideElements = [];
            if (selectedValue === DOR_SELECT) {
                showElements.push(dorTemplateRefField);
                hideElements.push(autoGenerateDorPanel);
                persistFields.push('dorTemplateRef');
                deleteFields.push('dorName', 'dorTitle', 'dorPath');
                manageFDViewPayload(dialog, true);
            } else if (selectedValue === DOR_GENERATE && !isFormEditor()) {
                hideElements.push(dorTemplateRefField);
                showElements.push(autoGenerateDorPanel);
                persistFields.push('dorName', 'dorTitle', 'dorPath');
                deleteFields.push('dorTemplateRef');
                manageFDViewPayload(dialog, false);
            } else {
                // DOR_NONE or DOR_GENERATE in form editor
                hideElements.push(dorTemplateRefField, autoGenerateDorPanel);
                deleteFields.push('dorName', 'dorTitle', 'dorPath', 'dorTemplateRef');
                if (selectedValue === DOR_GENERATE && isFormEditor()) {
                	manageFDViewPayload(dialog, false);
                } else {
                    manageFDViewPayload(dialog, true);
                }
            }

            manageElementVisibility(dialog, showElements, true);
            manageElementVisibility(dialog, hideElements, false);
            manageDeleteFields(dialog, deleteFields, true);
            manageDeleteFields(dialog, persistFields, false);

            setTimeout(function() {
                var selectedTab = dialog.find('coral-tab.is-selected');
                if (selectedTab.length > 0) {
                        selectedTab[0].invalid = false;
                    }
            });
        }

        // Handle DOR type selection change
        dorTypeSelector.addEventListener("change", updateDorUIBasedOnSelection);

        // Initialize the UI based on the current selection
        updateDorUIBasedOnSelection({target: {value: dorType.value}});
        
    }
    
        function registerDamAssetHandler(dialog) {
        if (isFormEditor()) {
            dialog.on("click", ".cq-dialog-submit", function (e) {
                var dorTypeField = dialog.find(DOR_TYPE)[0];
                if (!dorTypeField) {
                    return;
                }
                var currentFormContainerPath = Granite.author.selection.active.path;
                var damPath = currentFormContainerPath.replace(FM_AF_ROOT, DAM_ROOT);
                damPath = damPath.replace(CONTAINER, METADATA);
                var dorTypeValue = dorTypeField.value;
                // Prepare POST data
                var postData = {
                    './dorTemplateChanged': 'Boolean',
                    './dorType': dorTypeValue
                };
                
                if (dorTypeValue === DOR_SELECT) {
                    postData['./dorTemplateRef'] = dialog.find(DOR_TEMPLATE_REF_FIELD)[0].value;
                } else {
                    postData['./dorTemplateRef@Delete'] = '';
                }
                
                // Submit POST request without appending form to DOM
                $.ajax({
                    url: damPath,
                    type: 'POST',
                    data: postData,
                    success: function() {
                        // Request completed successfully
                    },
                    error: function(xhr, status, error) {
                        console.error('Error posting DOR metadata:', error);
                    }
                });
                
            });
        }
    }

    Utils.initializeEditDialog(EDIT_DIALOG)(handleDorTypeSelection, registerDamAssetHandler);

})(jQuery, Granite);