coverage:
  precision: 2
  round: nearest
  range: "70...90"
  status:
    project:
      default: off
      unittests:
        enabled: true
        target: 75%
        threshold: 10%
        base: auto
        flags: unittests
    patch:
      default: off
      unittests:
        enabled: true
        target: 75%
        threshold: 10%
        base: auto
        flags: unittests
flags:
  unittests:
    paths:
      - bundles/core/
