/*******************************************************************************
 * Copyright 2022 Adobe
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
(function (ns, document) {
    "use strict";

    var DOR_DIALOG_PATH = "fd/af/authoring/components/dor/dorPropertiesTabs",
        FD_VIEW_PATH = "/fd:view/print",
        PRINT_NODE_RELATIVE_PATH = "/jcr:content/guideContainer" + FD_VIEW_PATH,
        DOR_PREVIEW_SELECTOR = ".af.dor.pdf";

      var getFormPath = function (contentPath) {
                return contentPath.replace(Granite.HTTP.getContextPath(), "");
            },

            options = {};

    var dorPropertiesDialogConfig = function () {
            return {
                src : options.getPath() + '?resourceType=' + encodeURIComponent(DOR_DIALOG_PATH),
                isFloating : false,
                loadingMode : "auto",
                layout : "auto"
            };
        };

    var dorPropertiesDialogDef =  {
            getConfig : function getConfig() {
                return dorPropertiesDialogConfig();
            },
            getRequestedData : function getRequestedData() {
                return {
                    resourceType : DOR_DIALOG_PATH
                };
            },
            onOpen : ns.DialogFrame.openDialog,
            onReady : function onReady() {

            },
            onFocus : function onFocus() {

            },
            onSuccess :function() {console.log('success')},

            onClose : ns.DialogFrame.clearDialog,
            resourceType : DOR_DIALOG_PATH
        };
    var dorDialog = new ns.ui.Dialog(dorPropertiesDialogDef);

    window.CQ.FormsCoreComponents.editorhooks.openDorDialog =  function (editable) {
        var url = ns.ContentFrame.getContentPath() + PRINT_NODE_RELATIVE_PATH;
        if (!Granite.author.page.path.startsWith("/content/forms/af/")) {
            url = editable.path + FD_VIEW_PATH;
        }
        options.getPath = function () {
            return "/mnt/override/libs/" + DOR_DIALOG_PATH + "/cq:dialog.html" + url;
        };

         ns.DialogFrame.openDialog(function getDialog() {
             var editable = {
                 path : url.replace(Granite.HTTP.getContextPath(), ""),
                 type : DOR_DIALOG_PATH
             };
             dorDialog.editable = editable;
             return dorDialog;
         }());
    }

    window.CQ.FormsCoreComponents.editorhooks.initPreviewDoR = function(editable) {
        var url = getFormPath(ns.ContentFrame.getContentPath()) + "/jcr:content/guideContainer" + DOR_PREVIEW_SELECTOR;
        if (!Granite.author.page.path.startsWith("/content/forms/af/")) {
            url = editable.path + DOR_PREVIEW_SELECTOR;
        }
        window.open(Granite.HTTP.externalize(url), "_blank");
    }

    window.CQ.FormsCoreComponents.editorhooks.isAutoGenerateDoRConfigured = function(editable) {
        const formContainer = window.CQ.FormsCoreComponents.editorhooks.getComponentProperties(editable.path);
        let dorType;
        if (formContainer) {
            dorType = formContainer['dorType'];
        }
        return dorType === "generate";
    }

    function getStrongMarkup(strValue) {
        return "<strong>" + Granite.I18n.getMessage(strValue) + "</strong>";
    }

}(Granite.author, document));